DISCOUNT_RATE = 0.05
DELTA_T = 1
INV_HORIZON_DSO = 30
UNIT_COST_SUBS_HV = 0.0002             #[k€/VA]
UNIT_COST_SUBS_MV = 0.0003             #[k€/VA]
UNIT_COST_LOSSES = 0.0001             #[k€/kWh]
ENERGY_COST_IMP = 0.00035            #[k€/kWh]
ENERGY_COST_EXP = 0.0000          #[k€/kWh]
M = 1000
MAX_VOLTAGE = 1.05
MIN_VOLTAGE = 0.95
OMEGA = 1000
UNIT_COST_INV = 0.00016                 #[k€/VA]
UNIT_COST_PV = 0.1                      #[k€/m2]
INST_COST_PV = 1                        #[k€/unit]
INST_COST_HV_SUB = 10                   #[k€/unit]
INST_COST_MV_SUB = 100                  #[k€/unit]  
INST_COST_STORAGE = 1.5                 #[k€/unit] 
STORAGE_CAPACITY_COST = 0.44             #[k€/kWh]
STORAGE_POWER_COST = 0.16               #[k€/kW]
STORAGE_EFFICIENCY = 0.9
STORAGE_DAILY_MAX_VARIATION = 1
SURFACE_MULTIPLIER = 10

