# config.yml
time_series:
  default:
    source: "DATA.csv"
    csv_options:
        delim: ","
    timestamp: "Date"
    sampling_time: "Hour(1)"
    weight: 1

  # Define each profile you want to consider
  P1:
    value_column: "P1"
  P2:
    value_column: "P2"
  P3:
    value_column: "P3"
  P4:
    value_column: "P4"
  P5:
    value_column: "P5"
  P6:
    value_column: "P6"
  P7:
    value_column: "P7"
  P8:
    value_column: "P8"
  P9:
    value_column: "P9"
  P10:
    value_column: "P10"
  P11:
    value_column: "P11"
  P12:
    value_column: "P12"
  P13:
    value_column: "P13"
  P14:
    value_column: "P14"
  P15:
    value_column: "P15"
  P16:
    value_column: "P16"
  P17:
    value_column: "P17"
  P18:
    value_column: "P18"
  P19:
    value_column: "P19"
  P20:
    value_column: "P20"
  P21:
    value_column: "P21"
  P22:
    value_column: "P22"
  P23:
    value_column: "P23"
  P24:
    value_column: "P24"
  P25:
    value_column: "P25"
  P26:
    value_column: "P26"
  P27:
    value_column: "P27"
  P28:
    value_column: "P28"
  P29:
    value_column: "P29"
  P30:
    value_column: "P30"
  P31:
    value_column: "P31"
  P32:
    value_column: "P32"
  P33:
    value_column: "P33"
  P34:
    value_column: "P34"
  P35:
    value_column: "P35"
  P36:
    value_column: "P36"
  P37:
    value_column: "P37"
  Q1:
    value_column: "Q1"
  Q2:
    value_column: "Q2"
  Q3:
    value_column: "Q3"
  Q4:
    value_column: "Q4"
  Q5:
    value_column: "Q5"
  Q6:
    value_column: "Q6"
  Q7:
    value_column: "Q7"
  Q8:
    value_column: "Q8"
  Q9:
    value_column: "Q9"
  Q10:
    value_column: "Q10"
  Q11:
    value_column: "Q11"
  Q12:
    value_column: "Q12"
  Q13:
    value_column: "Q13"
  Q14:
    value_column: "Q14"
  Q15:
    value_column: "Q15"
  Q16:
    value_column: "Q16"
  Q17:
    value_column: "Q17"
  Q18:
    value_column: "Q18"
  Q19:
    value_column: "Q19"
  Q20:
    value_column: "Q20"
  Q21:
    value_column: "Q21"
  Q22:
    value_column: "Q22"
  Q23:
    value_column: "Q23"
  Q24:
    value_column: "Q24"
  Q25:
    value_column: "Q25"
  Q26:
    value_column: "Q26"
  Q27:
    value_column: "Q27"
  Q28:
    value_column: "Q28"
  Q29:
    value_column: "Q29"
  Q30:
    value_column: "Q30"
  Q31:
    value_column: "Q31"
  Q32:
    value_column: "Q32"
  Q33:
    value_column: "Q33"
  Q34:
    value_column: "Q34"
  Q35:
    value_column: "Q35"
  Q36:
    value_column: "Q36"
  Q37:
    value_column: "Q37"
  SUN:
    value_column: "SUN"

method:
  options:
    representative_periods: 4
    time_steps_per_period: 96
    total_periods: 8760  # Assuming 1 year of hourly data
    sampling_time: "Hour(1)"
  
  optimization:
    duration_curve_error:
      weight: 0.5
      number_bins: 40

results:
  save_results: true
  result_dir: "results"
  create_plots: true